### ISSUE TITLE
Why does redux-devtools need to be installed locally?

### ISSUE THREAD

**Issue by poshaughnessy** [Izzimach/r3test#1]
Hi Gary,

Just a question please: I saw the instruction about installing `redux-devtools` locally, but I figured I could just point to the `next` branch by configuring NPM like so:

```
"redux-devtools": "https://github.com/gaearon/redux-devtools.git#next"
```

`npm install` ran fine and it appeared to be there under `node_modules`. But running it up with `npm run dev` gave:

```
ERROR in ./src/r3test.js
Module not found: Error: Cannot resolve module 'redux-devtools' in /Users/peter/dev/src/misc/forks/r3test-fork/src
 @ ./src/r3test.js 40:21-46

ERROR in ./~/redux-devtools-log-monitor/lib/LogMonitor.js
Module not found: Error: Cannot resolve module 'redux-devtools' in /Users/peter/dev/src/misc/forks/r3test-fork/node_modules/redux-devtools-log-monitor/lib
 @ ./~/redux-devtools-log-monitor/lib/LogMonitor.js 37:21-46
```

Then I tried a [local npm pack](http://podefr.tumblr.com/post/30488475488/locally-test-your-npm-modules-without-publishing) and that seems to be working fine. I haven't been able to work out why yet though - please might you be able to explain?

Thanks!

**Comment by Izzimach** [comment]
I'm actually not sure. I think it's because you need the results of `npm run build`. Just pointing at the github repository just gives you the files but doesn't build them. I would guess that doing a local pack also performs the build step which is why that works for you.

**Comment by ironwren** [comment]
I'm seeing the same thing.

**Comment by vyorkin** [comment]
@bjrenfrow @Izzimach @poshaughnessy I believe it happens due to new npm policy about _not installing_ peerDependencies by default:

```
~/github/r3test master
❯ npm i
npm WARN EPEERINVALID react-three@0.7.3 requires a peer of react@0.14.2 but none was installed.
npm WARN EPEERINVALID react-three@0.7.3 requires a peer of react-dom@0.14.2 but none was installed.
npm WARN EPEERINVALID redux-devtools-dock-monitor@1.0.0-beta-3 requires a peer of redux-devtools@^3.0.0-beta-3 but none was installed.
npm WARN EPEERINVALID redux-devtools-log-monitor@1.0.0-beta-3 requires a peer of redux-devtools@^3.0.0-beta-3 but none was installed.

~/github/r3test master
❯ npm --version
3.4.0
```

I'll submit a PR.
