### ISSUE TITLE
Running the demo

### ISSUE THREAD

**Issue by og2t** [Izzimach/r3test#3]
I've cloned the `redux-devtools` inside the project and successfully run `npm install redux-devtools` but still getting these errors:

```
ERROR in ./src/r3test.js
Module not found: Error: Cannot resolve module 'redux-devtools' in /Users/tomek.augustyn/Desktop/r3test/src
 @ ./src/r3test.js 40:21-46

ERROR in ./~/redux-devtools-log-monitor/lib/LogMonitor.js
Module not found: Error: Cannot resolve module 'redux-devtools' in /Users/tomek.augustyn/Desktop/r3test/node_modules/redux-devtools-log-monitor/lib
 @ ./~/redux-devtools-log-monitor/lib/LogMonitor.js 27:21-46
webpack: bundle is now VALID.
```

Any ideas? Thanks!

**Comment by Izzimach** [comment]
Looks like there is no longer a `next` branch in `react-devtools` so they have probably updated versions. You may be able to just use the version of `react-devtools` in npmjs. If not, some other code may have to be updated.

**Comment by Izzimach** [comment]
Appears to work with v3.1.1 of `react-devtools`, let me know if something is broken.

**Comment by og2t** [comment]
Nah, doesn't work for me. Would you be able to put the demo online?
